sudo: false
dist: trusty

language: node_js
node_js:
  - node

cache:
  directories:
    - "node_modules"

addons:
  chrome: stable

install:
  - npm install -g @angular/cli
  - npm install

script:
  - npm test-ci
  - npm run e2e