sudo: false
dist: trusty

language: node_js
node_js:
  - node

addons:
  chrome: stable

install:
  - npm install -g @angular/cli

script:
  - npm run apply:copay
  - npm run test-ci
  - npm run e2e
  - npm run apply:bitpay
  - npm run test-ci
  - npm run e2e