sudo: false
dist: trusty

language: node_js
node_js:
  - node

addons:
  chrome: stable

env:
  - DISTRIBUTION=copay
  - DISTRIBUTION=bitpay

install:
  - npm install -g @angular/cli

script:
  - npm run apply:$DISTRIBUTION
  - npm run test-ci
  - npm run e2e